### ISSUE TITLE
Killing the statsd thread kills the calling thread

### ISSUE THREAD

**Issue by tswelsh** [tibbe/ekg-statsd#19]
We are using `forkStatsd` to start collecting stats, and later on stopping the stats collection by calling `killThread` on the `statsdThreadId`, as indicated in the documentation.  However, the implementation of `forkStatsd` rethrows _all_ exceptions coming from the forked thread to the thread that called `forkStatsd` in the first place, including any `ThreadKilled` exceptions.  This was confusing to say the least!

Is this the expected behaviour, or am I missing a better way of doing this?  It feels a bit clumsy to control the `Statsd` by throwing an exception that you then have to remember to catch, and you have no guarantee that the exception you catch is the one you threw in the first place.  This also feels inconsistent with a normal `forkIO` which swallows `ThreadKilled` (and `Blocked*`) exceptions so you don't see them in the main thread.

**Comment by tibbe** [comment]
Rethrowing that exception back to the caller wasn't intended.
