### ISSUE TITLE
GHC 8.10 support

### ISSUE THREAD

**Issue by ejconlon** [tibbe/ekg-statsd#27]
Needs base upper bound bump. See https://github.com/commercialhaskell/stackage/issues/5365

**Comment by ejconlon** [comment]
CI change here: https://github.com/tibbe/ekg-statsd/pull/29 . It looks like master is unreleased, so I am planning to upload that when the CI change lands rather than simply editing the Hackage revision for the last version.

**Comment by 23Skidoo** [comment]
Sure, please don't forget to update the changelig.

**Comment by ejconlon** [comment]
Released as https://hackage.haskell.org/package/ekg-statsd-0.2.4.1
